API/urls.py
from django.urls import path,include



urlpatterns = [
    path('', include("User.urls")),

]

User/urls.py
from django.urls import path,include
from User import views
app_name="User"



urlpatterns = [
    path('District/',views.District, name="District"),
    path('deletedistrict/<int:did>',views.DeleteDistrict,name="DeleteDistrict"),
    path('Updatedis/<int:uid>' , views.Updatedis,name="Updatedis"),


    path('Category/',views.Category, name="Category"),
    path('deletecategory/<int:did>',views.DeleteCategory,name="DeleteCategory"),
    path('Updatecat/<int:uid>' , views.Updatecat,name="Updatecat"),
    

    path('Place/', views.placeInsertSelect,name="placeInsertSelect"),
    path('delPlace/<int:did>', views.delPlace,name="delPlace"),
    path('placeupdate/<int:eid>',views.placeupdate,name="placeupdate"),


]

User/models.py
from django.db import models


class tbl_district(models.Model):
    district_name=models.CharField(max_length=50)


class tbl_place(models.Model):
    place_name=models.CharField(max_length=50)
    district=models.ForeignKey(tbl_district,on_delete=models.CASCADE)

User/views.py
from django.shortcuts import render, redirect
from API.db_utils import *

def District(request):
    data = fetch_districts()
    if request.method == "POST":
        district_name = request.POST.get("txt_district")
        insert_district(district_name)
        return redirect('User:District')
    return render(request, "User/District.html", {"District": data})

def DeleteDistrict(request, did):
    delete_district(did)
    return redirect("User:District")

def Updatedis(request, uid):
    dis = fetch_district_by_id(uid)
    if request.method == "POST":
        district_name = request.POST.get("txt_district")
        update_district(uid, district_name)
        return redirect("User:District")
    return render(request, "User/District.html", {"disdata": dis})

# Category Views
def Category(request):
    data = fetch_categories()
    if request.method == "POST":
        category_name = request.POST.get("txt_category")
        insert_category(category_name)
        return redirect('User:Category')
    return render(request, "User/Category.html", {"Category": data})

def DeleteCategory(request, did):
    delete_category(did)
    return redirect("User:Category")

def Updatecat(request, uid):
    cat = fetch_category_by_id(uid)
    if request.method == "POST":
        category_name = request.POST.get("txt_category")
        update_category(uid, category_name)
        return redirect("User:Category")
    return render(request, "User/Category.html", {"catdata": cat})

# Place Views
def placeInsertSelect(request):
    districts = fetch_districts()
    data = fetch_places()
    if request.method == "POST":
        place_name = request.POST.get('txtname')
        district_id = request.POST.get('sel_district')
        insert_place(place_name, district_id)
        return redirect("User:placeInsertSelect")
    return render(request, "User/Place.html", {'data': data, "districtdata": districts})

def delPlace(request, did):
    delete_place(did)
    return redirect("User:placeInsertSelect")

def placeupdate(request, eid):
    districts = fetch_districts()
    editdata = fetch_place_by_id(eid)
    if request.method == "POST":
        place_name = request.POST.get("txtname")
        district_id = request.POST.get('sel_district')
        update_place(eid, place_name, district_id)
        return redirect("User:placeInsertSelect")
    return render(request, "User/Place.html", {"editdata": editdata, "districtdata": districts})

templates/User/District.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>District</title>

   

    </head>


    <body>

    <form name="frmDistrict" method="POST">
        {% csrf_token %}
    <table align="center">
        <tr>
            <td>District</td>
            <td><input type="text" name="txt_district" placeholder="Enter District" value="{{disdata.district_name}}"></td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" name="btn_save" id="btn_save" value="Save">
            <input type="reset" name="btn_cancel" id="btn_cancel" value="Cancel"></td>
            </tr>
    </table>
</form>
    
</body>
</html>
    
    <table  border="1" align="center">
        <tr>
            <th>Sl.no</th>
            <th>District</th>
            <th>Action</th>
        </tr>
        {%  for i in District %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{i.district_name}}</td>
            <td><a href="{%  url 'User:DeleteDistrict' i.id %}">Delete</a> &nbsp;<a href="{%  url 'User:Updatedis' i.id %}">Edit</a></td>
        </tr>
        {% endfor %}
        </table>


   

templates/User/HomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello</h1>
</body>
</html>

templates/User/Place.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Place</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <table align="center">
            <tr>
                <td>District</td>
                <td>
                    <select name="sel_district" id="sel_district">
                        <option value="">...Select...</option>
                        {% for i in districtdata %}
                        <option 
                        {% if i.id == editdata.district_id %}
                        selected
                        {% endif %}
                        value="{{i.id}}">{{i.district_name}}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>PlaceName</td>
                <td><input type="text" name="txtname" placeholder="Enter Place" required value="{{editdata.place_name}}"></td>
            </tr>
            <tr>
                
                <td colspan="2" align="center">
                    <input type="submit" name="btnsubmit" value="Save">
                    <input type="reset" name="btncancel" value="Cancel">
                </td>
            </tr>
        </table>
    </form>

    <table border="1" align="center" cellpadding="10">
        <tr>
            <th>Sl.No</th>
            <th>District</th>
            <th>Place</th>
            <th>Action</th>
        </tr>
        {% for i in data %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{i.district_name}}</td>
            <td>{{i.place_name}}</td>
            <td><a href="{% url 'User:delPlace' i.id %}">Delete</a> | <a href="{% url 'User:placeupdate' i.id %}">Edit</a></td>
        </tr>
        {% endfor %}

    </table>

</body>
</html>